version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "bash scripts/start-server.sh"
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/code
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - '${MYSQL_FORWARD_PORT}:3306'