# Generated by Django 3.1.3 on 2020-12-27 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0001_initial'),
        ('folders', '0002_folders_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_images',
            name='shared_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shared_folders',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folders'),
        ),
        migrations.AddField(
            model_name='shared_folders',
            name='shared_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
