# Generated by Django 3.1.3 on 2020-12-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_images_owner'),
        ('albums', '0003_albums_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumshaveimages',
            name='id',
        ),
        migrations.AlterField(
            model_name='albumshaveimages',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='images.images'),
        ),
    ]
