# Generated by Django 3.1.3 on 2020-12-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='images',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
