# Generated by Django 3.1.3 on 2020-12-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_auto_20201219_1830'),
        ('images', '0002_auto_20201219_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='folder_id',
        ),
        migrations.AddField(
            model_name='images',
            name='folder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='folders.folders'),
        ),
    ]
