# Generated by Django 3.1.3 on 2020-12-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20201223_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shared_Images',
        ),
    ]
