# Generated by Django 3.1.3 on 2020-12-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_images_owner'),
        ('albums', '0002_albums_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='last_changed',
        ),
        migrations.AlterModelTable(
            name='albums',
            table='albums',
        ),
        migrations.CreateModel(
            name='AlbumsHaveImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.albums')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.images')),
            ],
            options={
                'db_table': 'albums_have_images',
            },
        ),
    ]
