# Generated by Django 3.1.3 on 2020-12-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20201220_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images_tags',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='images_tags',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
