# Generated by Django 3.1.3 on 2020-12-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20201221_0012'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='images_tags',
            table='images_tags',
        ),
    ]
