# Generated by Django 3.1.3 on 2020-12-20 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201219_1008'),
        ('tags', '0004_auto_20201221_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_tags',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tag', to='images.images'),
        ),
        migrations.AlterField(
            model_name='images_tags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_image', to='tags.tags'),
        ),
    ]
