# Generated by Django 3.1.3 on 2020-12-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201219_1008'),
        ('tags', '0005_auto_20201221_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='image',
            field=models.ManyToManyField(to='images.Images'),
        ),
    ]
