# Generated by Django 3.1.3 on 2020-12-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_tags_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='image',
        ),
    ]
