# Generated by Django 3.1.3 on 2020-12-22 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0007_remove_tags_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='tags',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
