# Generated by Django 3.1.3 on 2020-11-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20201121_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
