# Generated by Django 3.1.3 on 2020-11-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_remove_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
    ]
